-- DROP FUNCTION SALT;
CREATE FUNCTION SALT()
RETURNS CHAR(8)
EXTERNAL NAME 'udfhash!salt'
LANGUAGE C
PARAMETER STYLE SQL
DETERMINISTIC
NOT FENCED                                      -- May want to change this value
CALLED ON NULL INPUT
NO SQL
PROGRAM TYPE SUB
NO EXTERNAL ACTION;

